language: csharp
dist: trusty
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet build
  - zip * release.zip
  
deploy:
  provider: releases
  user: "hadagalberto"
  password: "Hadagalberto12."
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
